### ISSUE TITLE
Allow counting of branches that pass a certain cut

### ISSUE THREAD

**Issue by AvivCukierman** [kratsg/Optimization#29]
Given a list of branches (e.g. m_jet_largeR_0, m_jet_largeR_1, etc.), and a cut (e.g. ">200", or a window cut if that gets supported), create a value that counts the number of those branches that passed that cut. Then, allow us to cut on that value.

Perhaps in supercuts allow a flag called "derived" where you specify:
list of branches
initial cut (start,step,stop) (e.g. [200;100;500]) [or the initial cut could be fixed]
final cut (start,step,stop) (e.g. [0;1;4])

Note that if TA only stores the top 4 large R jets, e.g., as it currently does, then the final cut could only go from 0 to 4. But I think that would be fine (e.g. top tagging is usually 0-1).

**Comment by AvivCukierman** [comment]
This is a long term issue I think. Don't know how to apply labels.

**Comment by mswiatlo** [comment]
I agree we should have this, and hopefully sooner rather than later.

**Comment by mswiatlo** [comment]
Noting down for posterity:

If we use TTree, it's pretty easy to do something like:

(m_jet_largeR_0 > X) + (m_jet_largeR_1 > X) + (m_jet_largeR_2 > X) > Y as a specifiable user-cut-string, and then X and Y are entries in the supercuts to iterate over.
