### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by vikas-parashar** [kratsg/optimization#52]
This repo is missing a license. Without a license, all code is copyrighted to the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

A PSA called [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by kratsg** [comment]
Closed with 0b1033a53c9f950f804f511109619c689bb45da3
