### ISSUE TITLE
somethinga bout pileup weight being 0 and boolean

### ISSUE THREAD

**Issue by kratsg** [kratsg/Optimization#72]
return np.sum(events!=0).astype(float), np.sum(events).astype(float)`

[01:18]  
hrmm

[01:18]  
that's the bug

[01:18]  
hrmmm

[Giordon Stark but if you change the line I linked... to..

[01:21]  
`return float(events.size), np.sum(events).astype(float)`

[01:21]  
and see if that fixes it with the pileup weight added, my guess is it does.

[01:22]  
https://github.com/kratsg/Optimization/commit/0c9067d9ca5a88d5f8741adaa464e1b289fca474#diff-06f0ae61dbe721276333a254a24a044b

[01:22]  
yeah, i wonder why it changed :confused:

[

**Comment by mattleblanc** [comment]
See #73
