### ISSUE TITLE
Add window cuts

### ISSUE THREAD

**Issue by mswiatlo** [kratsg/Optimization#8]
Add another option to the cuts j-son, to flag a branch for exploration as a window cut. This is pretty easy to do in practice: you just have two iterators, for the start of the window and the end of the window. Start with the iterators some MINWINDOW size apart from each other, and advance the right-iterator by a step. Advance the left iterator to sweep all available windows. Reset the left iterator. Advance the right iterator. You can have an option to search for signal INSIDE the window, and outside the window (99% of the time we want inside, but just to be sure).

This is mostly useful for mass cuts on the re-clustered jets: would be good to see whether a window improves anything over a simple cut. 

I would not worry about extending the generator to this case; this is something we can specify manually, when we have a good reason to expect a particular branch to want a window.

**Comment by AvivCukierman** [comment]
Bump this issue
