### ISSUE TITLE
Add simple maths support

### ISSUE THREAD

**Issue by mswiatlo** [kratsg/Optimization#9]
Would be good to add simple branch math support. This is the ability to specify in the json that we want to scan over a variable like "BRANCH1 + BRANCH2." 

I'm not sure about the best way to do this, but TTree::Draw's branch manipulation syntax is very good at doing this sort of thing. I'm sure numpy has something clever as well.

**Comment by kratsg** [comment]
I would have to think more about this. To be honest, what's tricky is just building the branch. To be technical, `apply_cut()` doesn't do anything but just that -- apply the cut. We could make it something that gets pre-built, where the cuts to make are scanned over, and if it finds a math equation in one of them (looking for a + or - or * or /), then it will split it up and create a new temporary branch to make the cut on.

The other way is to do this upstream where you add the new branch to the ntuple (who cares about size at this point if you always run cuts over a subset of all branches) and then the script downstream doesn't care.
